### ISSUE TITLE
Review your LICENSE or delete it

### ISSUE THREAD

**Issue by DavidHaslam** [msavli/SloKJV#1]
GNU GPL 3.0 isn't the same as Public Domain.

You hade PD in the module .conf file.

Please decide what kind of license you want.

**Comment by msavli** [comment]
Changed into Public Domain.
If you fell that this is not appropriate, please tell.





       ------------   Marjan   ----------
        tel:    +386 (0)4 5121 377
        e-mail: marjan.savli@gmail.com
       --------------------------------------

2017-03-28 16:15 GMT+02:00 David Frank Haslam <notifications@github.com>:

**Comment by DavidHaslam** [comment]
Thanks!
