### ISSUE TITLE
Add a README.md file

### ISSUE THREAD

**Issue by DavidHaslam** [msavli/SloKJV#2]
Visitors may not know what a .conf file is.

Everyone using GitHub is familiar with a README.md file to learn what a repository is for.

Please create such a file and describe the project in both English and Slovenian.

**Comment by msavli** [comment]
Done.



       ------------   Marjan   ----------
        tel:    +386 (0)4 5121 377
        e-mail: marjan.savli@gmail.com
       --------------------------------------

2017-03-28 16:18 GMT+02:00 David Frank Haslam <notifications@github.com>:

**Comment by DavidHaslam** [comment]
Thanks!
