### ISSUE TITLE
subType="x-NT" missing in second bookGroup div

### ISSUE THREAD

**Issue by DavidHaslam** [msavli/SloKJV#3]
I think this was a simple omission.

**Comment by DavidHaslam** [comment]
Still not fixed.

**Comment by msavli** [comment]
I added
<div type="bookGroup" subType="x-NT"><title type="main">Nova zaveza</title>

Thanks

**Comment by DavidHaslam** [comment]
But that was not the required fix, albeit it's also a good change.
Currently you have:
```
<div type="bookGroup" subType="x-OT">
```
and for the NT merely
```
<div type="bookGroup">
```

The latter should have the attribute added, thus:
```
<div type="bookGroup" subType="x-NT">
```
