### ISSUE TITLE
TextSource in slokjva.conf

### ISSUE THREAD

**Issue by DavidHaslam** [msavli/SloKJV#4]
Please change line to read

`TextSource=https://github.com/msavli/SloKJVA`

as per email discussion.

**Comment by msavli** [comment]
Done in SloKJV in SloKJVDC.



       ------------   Marjan   ----------
        tel:    +386 (0)4 5121 377
        e-mail: marjan.savli@gmail.com
       --------------------------------------

2017-03-29 17:39 GMT+02:00 David Frank Haslam <notifications@github.com>:
