### ISSUE TITLE
Counted words list from verse text (excluding notes & titles, etc) FYI

### ISSUE THREAD

**Issue by DavidHaslam** [msavli/SloKJV#5]
The attached tab delimited text file extracts and counts all the words in the **SloKJV** source text.

"It's all part of the service!"

[SloKJV_sword.words.count.txt](https://github.com/msavli/SloKJV/files/2719271/SloKJV_sword.words.count.txt)

**Comment by msavli** [comment]
Fixed about 50 typos in source.

**Comment by DavidHaslam** [comment]
Yes - that’s exactly what a counted word list can facilitate. 

:)

**Comment by DavidHaslam** [comment]
[SloKJV words.xlsx](https://github.com/msavli/SloKJV/files/2723878/SloKJV.words.xlsx)

The extra columns in the updated word list facilitate different sorting orders.

This may bring to light further spelling/typing errors.

The **Reverse** column is inspired by the notion of a [Rhyming Dictionary](https://en.wikipedia.org/wiki/Rhyming_dictionary)

Enjoy!
