### ISSUE TITLE
Suggested minor change in OSIS header

### ISSUE THREAD

**Issue by DavidHaslam** [msavli/SloKJV#7]
Change
```
	<osisText osisIDWork="SloKJVA" osisRefWork="Bible" xml:lang="sl">
		<header>
			<work osisWork="SloKJVA"/>
		</header>
```
to
```
	<osisText osisIDWork="SloKJV" osisRefWork="Bible" xml:lang="sl">
		<header>
			<work osisWork="SloKJV"/>
		</header>
```

**Comment by msavli** [comment]
Changed script

echo.
echo Odstrani crko A iz   Work="SloKJVA"
%SED% -i "s/Work=\"SloKJVA\"/Work=\"SloKJV\"/g" %XML_SloEngKJVA%



       ------------   Marjan   ----------
        e-mail: marjan.savli@gmail.com
       --------------------------------------


V V sob., 5. jan. 2019 ob 18:37 je oseba David Frank Haslam <
notifications@github.com> napisala:
